[BPROC-51] - Melhora readme da aplicação
mundipagg/camaleao pull request #50
Opened 2021-03-15 13:43 UTC by thiagocoppi

| Perguntas     	        | Respostas
| ------------- 	        | -------------------------------------------------------
| Feature        	        | Não informado
| O que foi feito ?    | Melhora a documentação do readme
| Por que foi feito ? | Para facilitar o entendimento de como funciona a aplicação
| Como foi feito?     | Adiciona informações ao readme

#### Status
Pronto

2021-03-15 17:40 UTC, vpecanha requested changes

2021-03-15 17:40 UTC, vpecanha commented on README.md
> +> Caso esteja rodando a primeira vez, será aberto uma janela da qual você deve permitir a execução da aplicação
Acho que isso daqui é irrelevante dado a situação

2021-03-15 17:40 UTC, vpecanha commented on README.md
>  ## Contribuindo
Porque está fora do padrão dos outros repos?

2021-03-16 13:11 UTC, thiagocoppi commented
@vpecanha 
Pode revisar novamente?

2021-03-16 16:58 UTC, thiagocoppi commented
Resolvido as pendências @bruno-sales  @vpecanha

2021-03-17 14:57 UTC, leojasmim approved these changes

2021-03-17 15:12 UTC, bruno-sales approved these changes

2021-04-26 16:23 UTC, merged